### ISSUE TITLE
Ord instance for Set

### ISSUE THREAD

**Issue by AKST** [purescript/purescript-sets#10]
The [Haskell implementation](https://downloads.haskell.org/~ghc/7.8.2/docs/html/libraries/containers-0.5.5.1/src/Data-Set-Base.html#Set) of this is something like this.

```haskell
toAscList :: Set a -> [a]
toAscList = foldr (:) []

instance Ord a => Ord (Set a) where
    compare s1 s2 = compare (toAscList s1) (toAscList s2)
```

At the moment Array doesn't implement Ord either, so we can't just switch out `toAscList` for `toList`, so maybe that's also an issue? (Assuming the lack of an Ord instance is undesirable)

**Comment by paf31** [comment]
https://github.com/purescript/purescript-prelude#ordarray

**Comment by AKST** [comment]
Oh sweet, must of missed that (I was looking at data-arrays), since it's part of a problem I'm trying to solve I'm happy to put a pull request together

**Comment by paf31** [comment]
Ok cool. The Prelude currently lives both there, and in the compiler repo, so for now you don't need to add a dependency.
