### ISSUE TITLE
tag v0.4.2

### ISSUE THREAD

**Issue by kakkun61** [purescript/purescript-sets#23]
Please tag b2dc7b12ebe0d44674f044ee90759db6a6ccf48e as v0.4.2.
v0.4.1 cannot be compiled.

```
bower_components\purescript-sets\src\Data\Set.purs line 27, column 1 - line 28, column 1:
  Unknown module Data.Int
```

**Comment by garyb** [comment]
Done! https://github.com/purescript/purescript-sets/releases/tag/v0.4.2

**Comment by kakkun61** [comment]
Thank you.
