### ISSUE TITLE
Add map?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-sets#26]
I realise a `Functor` instance is not possible, but would a monomorphic `map` function be ok?

```
Data.Set.map :: forall a b. (a -> b) -> Set a -> Set b
```

**Comment by zudov** [comment]
I think this one should have an `Ord` constraint `map :: forall a b. (Ord b) => (a -> b) -> Set a -> Set b` and would basically be `fromList <<< map f <<< toList`, but of course we also may add a monotonic version like [`Data.Set.mapMonotonic`](http://haddock.stackage.org/lts-3.15/containers-0.5.6.2/Data-Set.html#v:mapMonotonic). It should be possible to make it *O(n)* but I would prefer such things to be in `Data.Set.Unsafe`.

**Comment by paf31** [comment]
I think both `map` and `Unsafe.mapMonotonic` could be useful :+1:

**Comment by LiamGoodacre** [comment]
:+1:

`Set.map` could actually be a version of `fromFoldable` which applies a function before inserting.  Given that we have `Foldable Set`.

~~~purescript
fromFoldable :: forall f a. (Foldable f, Ord a) => f a -> Set a
map :: forall f a b. (Foldable f, Ord b) => (a -> b) -> f a -> Set b
~~~

Alternatively, rename that to `fromFoldableBy` and then have an alias as `map` which is specific to `Set`.

~~~purescript
fromFoldableBy :: forall f a b. (Foldable f, Ord b) => (a -> b) -> f a -> Set b
fromFoldableBy f = foldl (\m a -> insert (f a) m) empty

map :: forall f a b. Ord b => (a -> b) -> Set a -> Set b
map = fromFoldableBy
~~~
